<?xml version="1.0"?>
<package format="3">
  <name>gz_terramechanics</name>
  <version>1.0.0</version>
  <description>Terramechanics plugin for Gazebo</description>

  <author email="simone.cottiga@phd.units.it">Simone Cottiga</author>
  <author email="khalid.bourr@gmail.com">Khalid BOURR</author>

  <maintainer email="simone.cottiga@phd.units.it">Simone Cottiga</maintainer>
  <maintainer email="khalid.bourr@gmail.com">Khalid BOURR</maintainer>


  <license>Apache-2.0</license>

  <buildtool_depend>cmake</buildtool_depend>
  
  <depend>gz-sim8</depend>
  <depend>gz-plugin2</depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>